Repository UpendoVentures/Upendo-DNN-Simple-Auth-Provider, pull requests merged in 2023-08, with the labels that each got.

#22 Tasks/1.0 release prep
  Modules/UpendoDnnSimpleAuthProvider/Components/AuthConfigBase.cs
  Modules/UpendoDnnSimpleAuthProvider/Components/Const.cs
  Modules/UpendoDnnSimpleAuthProvider/Components/Email.cs
  Modules/UpendoDnnSimpleAuthProvider/Components/Json.cs
  Modules/UpendoDnnSimpleAuthProvider/Components/RandomCodeGenerator.cs
  Modules/UpendoDnnSimpleAuthProvider/Components/UtilityMethods.cs
  Modules/UpendoDnnSimpleAuthProvider/Data/Cryptography/AesEncryption.cs
  Modules/UpendoDnnSimpleAuthProvider/Data/Cryptography/Base64.cs
  Modules/UpendoDnnSimpleAuthProvider/Data/Cryptography/Conversion.cs
  Modules/UpendoDnnSimpleAuthProvider/Data/Cryptography/Hashing.cs
  Modules/UpendoDnnSimpleAuthProvider/Data/Cryptography/KeyGenerator.cs
  Modules/UpendoDnnSimpleAuthProvider/Data/Cryptography/KeyManager.cs
  Modules/UpendoDnnSimpleAuthProvider/Data/Cryptography/TripleDesEncryption.cs
  Modules/UpendoDnnSimpleAuthProvider/Data/VerificationCodeRepository.cs
  Modules/UpendoDnnSimpleAuthProvider/License.txt
  Modules/UpendoDnnSimpleAuthProvider/Login.ascx.cs
  Modules/UpendoDnnSimpleAuthProvider/Logoff.ascx.cs
  Modules/UpendoDnnSimpleAuthProvider/Models/Interfaces/IVerificationCode.cs
  Modules/UpendoDnnSimpleAuthProvider/Models/VerificationCode.cs
  Modules/UpendoDnnSimpleAuthProvider/Module.build
  Modules/UpendoDnnSimpleAuthProvider/Properties/AssemblyInfo.cs
  Modules/UpendoDnnSimpleAuthProvider/Settings.ascx.cs
  Modules/UpendoDnnSimpleAuthProvider/UpendoDnnSimpleAuthProvider.dnn
  Modules/UpendoDnnSimpleAuthProvider/UpendoDnnSimpleAuthProvider_Symbols.dnn
  Modules/UpendoDnnSimpleAuthProvider/UpendoVentures.Auth.UpendoDnnSimpleAuthProvider.csproj
  Modules/UpendoDnnSimpleAuthProvider/packages.config
  Modules/UpendoDnnSimpleAuthProvider/releasenotes.txt
  Upendo.DNN.SimpleAuth.sln
Labels: enhancement

#26 Tasks/v1 release prep
  Modules/UpendoDnnSimpleAuthProvider/App_LocalResources/Login.ascx.resx
  Modules/UpendoDnnSimpleAuthProvider/Properties/AssemblyInfo.cs
  Modules/UpendoDnnSimpleAuthProvider/UpendoDnnSimpleAuthProvider.dnn
  Modules/UpendoDnnSimpleAuthProvider/UpendoDnnSimpleAuthProvider_Symbols.dnn
Labels: task

#28 Update README.md
  README.md
Labels: enhancement

#32 Tasks/release prep
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/help-and-other-questions.md
  Modules/UpendoDnnSimpleAuthProvider/Templates/EmailTemplate.html
  Modules/UpendoDnnSimpleAuthProvider/UpendoVentures.Auth.UpendoDnnSimpleAuthProvider.csproj
Labels: task

#41 Syncing `main` and `dev`
  .github/ISSUE_TEMPLATE/bug-report.md
  Modules/UpendoDnnSimpleAuthProvider/App_LocalResources/Login.ascx.resx
  Modules/UpendoDnnSimpleAuthProvider/Components/DnnGlobal.cs
  Modules/UpendoDnnSimpleAuthProvider/Components/Email.cs
  Modules/UpendoDnnSimpleAuthProvider/Components/UtilityMethods.cs
  Modules/UpendoDnnSimpleAuthProvider/Login.ascx.cs
  Modules/UpendoDnnSimpleAuthProvider/Login.ascx.designer.cs
  Modules/UpendoDnnSimpleAuthProvider/Properties/AssemblyInfo.cs
  Modules/UpendoDnnSimpleAuthProvider/Templates/EmailTemplate.html
  Modules/UpendoDnnSimpleAuthProvider/UpendoDnnSimpleAuthProvider.dnn
  Modules/UpendoDnnSimpleAuthProvider/UpendoDnnSimpleAuthProvider_Symbols.dnn
  Modules/UpendoDnnSimpleAuthProvider/releasenotes.txt
Labels: task

#48 Fix_Multiple_Authentication_Provider_Display_Issues
  Modules/UpendoDnnSimpleAuthProvider/Module.css
Labels: bug

#44 Update_Enable/Disable_Setting
  Modules/UpendoDnnSimpleAuthProvider/Components/AuthConfigBase.cs
  Modules/UpendoDnnSimpleAuthProvider/Settings.ascx.cs
Labels: enhancement

#50 Tasks/release prep 1.0.2
  Modules/UpendoDnnSimpleAuthProvider/Login.ascx
  Modules/UpendoDnnSimpleAuthProvider/Properties/AssemblyInfo.cs
  Modules/UpendoDnnSimpleAuthProvider/UpendoDnnSimpleAuthProvider.dnn
  Modules/UpendoDnnSimpleAuthProvider/UpendoDnnSimpleAuthProvider_Symbols.dnn
  Modules/UpendoDnnSimpleAuthProvider/releasenotes.txt
Labels: bug

#51 Fix_Missed_Localizing_Messages
  Modules/UpendoDnnSimpleAuthProvider/App_LocalResources/Login.ascx.resx
  Modules/UpendoDnnSimpleAuthProvider/Login.ascx
  Modules/UpendoDnnSimpleAuthProvider/Login.ascx.cs
Labels: bug

#54 Regenerated the missing updates from the designer file
  Modules/UpendoDnnSimpleAuthProvider/Login.ascx
  Modules/UpendoDnnSimpleAuthProvider/Login.ascx.designer.cs
Labels: bug

#55 Syncing dev and main
  Modules/UpendoDnnSimpleAuthProvider/Login.ascx
  Modules/UpendoDnnSimpleAuthProvider/Login.ascx.designer.cs
Labels: task

#58 Resolve_Usability_Bug_With_Enabling_Or_Disabling_The_Providers
  Modules/UpendoDnnSimpleAuthProvider/Login.ascx
  Modules/UpendoDnnSimpleAuthProvider/Login.ascx.cs
  Modules/UpendoDnnSimpleAuthProvider/Providers/DataProviders/SqlDataProvider/01.00.00.SqlDataProvider
  Modules/UpendoDnnSimpleAuthProvider/Providers/DataProviders/SqlDataProvider/Uninstall.SqlDataProvider
  Modules/UpendoDnnSimpleAuthProvider/UpendoVentures.Auth.UpendoDnnSimpleAuthProvider.csproj
  Modules/UpendoDnnSimpleAuthProvider/Utility/UpendoDnnSimpleAuthConfig.cs
Labels: bug
